---
apiVersion: v1
kind: Service
metadata:
  name: world-gift-art-service
  namespace: world-gift-art-staging
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    frontedBy: world-gift-art-staging # will be applied to backends by Spinnaker
  type: LoadBalancer
  loadBalancerIP: ""
